fix: Remove appium from dev dependencies (#1417)

diff --git a/ci-jobs/templates/ios-e2e-template.yml b/ci-jobs/templates/ios-e2e-template.yml
--- a/ci-jobs/templates/ios-e2e-template.yml
+++ b/ci-jobs/templates/ios-e2e-template.yml
@@ -50,9 +50,34 @@ jobs:
     - task: NodeTool@0
       inputs:
         versionSpec: 16.x
-    - script: npm install
+    - script: |
+        npm install -g appium@next
+        npm install
       displayName: Install node dependencies
-    - script: export PATH="${PATH}:$(python -c 'import site; print(site.USER_BASE)')/bin" && ${{ parameters.script }}
+    - script: |
+        export APPIUM_TEST_SERVER_PORT=4567
+        export APPIUM_TEST_SERVER_HOST=127.0.0.1
+        export cwd=$(pwd)
+        pushd "$cwd"
+        cd ~
+        appium driver install --source=local "$cwd"
+        appium server \
+          --port=$APPIUM_TEST_SERVER_PORT \
+          --address=$APPIUM_TEST_SERVER_HOST \
+          --relaxed-security \
+          &
+        popd
+        secondsStarted=$(date +%s)
+        while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+          sleep 0.1
+          secondsElapsed=$(( $(date +%s) - secondsStarted ))
+          if [[ $secondsElapsed -gt 30 ]]; then
+            echo "Appium server was unable to start within 30 seconds timeout"
+            exit 1
+          fi
+        done
+
+        export PATH="${PATH}:$(python -c 'import site; print(site.USER_BASE)')/bin" && ${{ parameters.script }}
       displayName: Run functional tests
     - task: PublishTestResults@2
       condition: always()
